//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbx_aspweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc
    {
        public int id { get; set; }
        public int pos_x { get; set; }
        public int pos_y { get; set; }
        public int region_id { get; set; }
        public int npc_type_id { get; set; }
    
        public virtual npc_type npc_type { get; set; }
        public virtual region region { get; set; }
    }
}
