//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbx_aspweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int id { get; set; }
        public string name { get; set; }
        public double health { get; set; }
        public double skill_level { get; set; }
        public int birth_date { get; set; }
        public int pos_x { get; set; }
        public int pos_y { get; set; }
        public string login_name { get; set; }
        public string login_password { get; set; }
        public int region_id { get; set; }
        public int admin { get; set; }
    
        public virtual region region { get; set; }
    }
}
