//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbx_aspweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public region()
        {
            this.npcs = new HashSet<npc>();
            this.players = new HashSet<player>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<npc> npcs { get; set; }
        public virtual ICollection<player> players { get; set; }
    }
}
